### ISSUE TITLE
Cách dùng hàm NewWithLunar

### ISSUE THREAD

**Issue by minhdanh** [hungtrd/amlich#3]
Chào bạn, cho mình hỏi cách dùng hàm NewWithLunar. Cụ thể là khi dùng hàm này cần có biến leap (bool).
Vậy làm sao để mình biết được ngày âm lịch muốn khởi tạo là có bool bằng true hay false?

Ví dụ mình muốn tạo 1 ngày âm lịch: 1/12/2009
NewWithLunar(1, 12, 2009, l bool, loc)
-> thì chỗ l nên dùng thế nào?

Cảm ơn bạn

**Comment by hungtrd** [comment]
@minhdanh Hi bạn. Giá trị leap ở đây là để chỉ tháng nhuận.
Ví dụ như năm 2023 có 2 tháng Hai âm lịch.
Thì tháng Hai đầu tiên sẽ là tháng Hai bình thường leap = false
còn tháng Hai tiếp theo sẽ là tháng Hai nhuận leap = true
nên để xác định 1 tháng âm lịch thì sẽ phải kèm theo tháng đó có phải tháng nhuận hay k

**Comment by minhdanh** [comment]
Vậy tức là với một ngày âm lịch cho trước, mình phải tự xác định xem ngày âm lịch đó có tháng nhuận hay không trước khi khởi tạo với `NewWithLunar` đúng không bạn?

**Comment by hungtrd** [comment]
Đúng r bạn :+1:

**Comment by minhdanh** [comment]
Cảm ơn bạn
